### ISSUE TITLE
Finishing the Mobula

### ISSUE THREAD

**Issue by Elyssaen** [Elyssaen/trin#1]
The Mobula battlecruiser is still a WIP. It's a bigger brother to the Chimaera that was designed to be the Trin's first dedicated battlecruiser. It will be very rare, as it was only rolled out in one Trin Sept and didn't see action before the fall. The current model is likely to be a little overpowered, but we'll see.

The target is that a Mobula can't beat an Antiarch one-on-one, or even come that close, but it will outperform the Antiarch against the Quarg and _especially_ against Archons. No ship should be better against Archons than this one, although it's still nowhere _near_ a match one-on-one (we're talking 4 or 5 at least).

I'm trying to hit the relative balance by:

1. eschewing Piranhas, which are great against many foes but useless against the Quarg and Drak;
2. eschewing missiles for a similar reason, because at least the Archons are able to shoot them down easily;
3. using the unique Warp Ray to prevent escape and help neutralise both the Drak Distancer and the Antimatter Cannon;
4. like the Chimaera (also designed to fight the Quarg specifically), make strong use of Matrix Guns (for heavy firepower) and Stasis Snares, rather than the more versatile but less powerful Matrix Batteries.

**To-Do**
- [ ] Do another round of testing to see how the balance is at the moment.
- [ ] Warp Ray sprite: upgrade it to something a bit better than a scaled Quarg Skylance placeholder!
- [x] Make sure the Swivel Matrix Guns are actually giving the advantage over the basic Matrix Guns that I expect.
- [x] Consider upping the crew after assessing how close to obtainable they might be. (They're not obtainable yet, but other new content might change that and I need to balance the story reasons for them to have a relatively low crew with future balance considerations.)
- [x] Look for any areas I can _weaken_ the Mobula will still hitting all objectives.
