### ISSUE TITLE
The Trin Queen arc

### ISSUE THREAD

**Issue by Elyssaen** [Elyssaen/trin#10]
This is a moderate length storyline where you encounter a barely surviving intelligent Trin and hear about their history from her perspective. You have the choice of helping her survive by fetching her Trin technology so she can keep her life support functioning, or telling the Quarg about her.

**To-Do**
- [ ] Finish writing the core story.
- [ ] Write the betrayal mission(s).
- [ ] When feature/GiftShip (#8) is done, add a final reward of a Trin Chimaera.
