### ISSUE TITLE
Finish balancing document

### ISSUE THREAD

**Issue by Elyssaen** [Elyssaen/trin#11]
I have a balancing document that's in progress. Need to finish it (at least outfitting) and push it up so there's some reference to why I've picked the numbers I have.

**To-Do**
- [ ] **trin outfits.txt**: rewrite Strangelet reactors' balancing since the rebalance (adding Adapters).
- [ ] **trin weapons.txt**: write.
- [ ] **trin ships.txt**: write.
- [ ] Set up a Documentation/Reference directory for the project.
