### ISSUE TITLE
feature/TurretFiringArc

### ISSUE THREAD

**Issue by Elyssaen** [Elyssaen/trin#12]
Branch: [feature/TurretFiringArc](https://github.com/Elyssaen/endless-sky/tree/feature/TurretFiringArc)

The Mobula is like a Tier 3 super-Vanguard, a battlecruiser that relies on enormous forward-firing firepower, but unfortunately the stocky triangular frame with guns across the width creates serious convergence problems. It wouldn't be so bad, except Matrix Guns converge at their maximum 960 range but are most effective when _much_ closer than that (within 120).

This code dependency is designed to give Mobulas a weapon inbetween the Matrix Gun and the giant, damage-limited Matrix Batteries. (As well as being a triple Matrix Gun turret, Matrix Batteries have a 'limiter' that caps their damage so the Skylance+ type DPS/t in 0-120 range isn't carried over.)

The idea is Mobulas will use 4 Swivel Matrix Guns instead of 8 Matrix Guns, and a Swivel Matrix Gun (may be called a 'Matrix Array') will be a twin gun with a swivel arc of about 30 degrees either side. The gun isn't actually physically swivelling: it's using some sort of [phased array](https://en.wikipedia.org/wiki/Phased_array).

**To-Do**
- [x] Get the "swivel degrees" weapon attribute coming into the code.
- [x] Have a weapon that uses a turret mount, but has no "swivel degrees" specified, default to the maximum (180 degrees either way for full 360 degree coverage).
- [x] Get swivel weapons able to fire only within the allowed arc.
- [x] Update the AI's missile boat code so that it can handle 'inbetween'-type swivel guns. Right now, missile boat AI triggers if every turret has a range of at least 1000 and every gun of at least 2000. Swivel guns will choose a value inbetween depending on how wide an arc they can shoot over.
- [x] Update the AI's AutoFire function so that it knows how to fire swivel guns.
- [x] Check any other reference to a turret in the code to look for any other special handling of guns vs turrets, and make sure swivel weapons are compatible throughout.

**Comment by Elyssaen** [comment]
Created this issue (having marked it as 'done') because of the AutoFire problem I noticed. Hadn't occurred to me the AI wouldn't know how to fire them, but it shouldn't be too difficult to update the behaviour.

I'm currently playing the new Wanderer content and looking into something else, but I'll get back on to this shortly and then onto the other issues for this milestone.

_Edit:_ should be done now.

**Comment by Elyssaen** [comment]
Obviously, something else was going to go wrong. Was testing the Mobula balance when I noticed that Makos were having difficulty firing their missiles, and figured out I'd introduced a bug in homing weapon targeting in the last commit. Fixed now.
