### ISSUE TITLE
Next round of work on raid missions

### ISSUE THREAD

**Issue by Elyssaen** [Elyssaen/trin#2]
The invisible Trin raid missions in Hai, Wanderer and Korath space are the backbone of the content. The original plan was that an invisible mission would trigger the Trin attacking a _random_ system, but as the Quarg should come to the aid of any raid in Hai or Efreti space, and two different NPC specifications can't yet head to the same random location, that's out.

The raid missions are in place already but some new work is needed before pushing up:

**To-Do**
- [x] _Remove the Empyreal Field: it doesn't serve a defined purpose and has a bad habit of disabling allied Trin Piranhas right now. Might come back at some time later when MZ has implemented aura weapons. Not entirely related to raid missions, but a minor task I need to do before getting on with this._
- [ ] _Rebalance the Cachalot a bit: another minor task._
- [ ] Revisit every Trin variant ship, because a lot of balance changes have been made since then and there's no guarantee many of them even make sense anymore.
- [ ] Rebalance all the different Trin fleet sizes and the prevalence of different variant types. Particularly, Marlins should be _very_ rare and only appear in Wanderer space, and Mobulas similarly rare and only appear in Korath space.
- [x] Add more Quarg Reinforcement variant types: decide if they'll only field Wardragons on these tough battles or if they're happy to send in Skylarks.
- [x] Don't allow raid missions to be concurrent, so different types can't all trigger at once and overwhelm the player.
- [ ] _**(Next Sprint)**_ Because the mission doesn't fail/end until you next land, and the only Quarg NPC behaviour that will get them to your system from Quarg space will also make them follow the player, you currently get a free Quarg escort until you next land. Need to fix this somehow, but it might require a new code dependency.
- [ ] _**(Next Sprint)**_ The Trin might sometimes fail to show up. I've had this with `entering` before and don't know what causes it yet.

A potential fix to both the last two issues would be a new code dependency I'm considering, feature/NPCTravelTo, which would allow a mission NPC to be given a location they're supposed to travel to. A characteristic like "staying" would apply once they've reached their destination. It'd also be a useful feature for a dozen other reasons, so it's on my general list anyway.
