### ISSUE TITLE
The Dreadhand arc

### ISSUE THREAD

**Issue by Elyssaen** [Elyssaen/trin#6]
This is a short storyline where a dangerous pirate challenges you to a duel, and shows up with some pretty unusual (read: Trin) technology.

**To-Do**
- [ ] Customise the Dreadhand's hail messages, probably with a custom government.
- [x] Improve the Stolen Hyperdrive/Scram Drive/Jump Drive/Shunt Drive mission text so that if you show up with more than one type of drive, the text doesn't clash too badly.
- [ ] Key a different outcome in the "on complete" conversation based on if you cheated and brought a fleet (it's possible, although it doesn't seem like it is).
- [ ] Finish writing the story.
